# Generated by Django 4.1.1 on 2022-09-24 02:19

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('nombre_usuario', models.CharField(max_length=100)),
                ('correo', models.EmailField(max_length=254)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('subtitulo', models.CharField(max_length=250)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='posts')),
                ('cuerpo', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('autor', models.CharField(max_length=50)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('usuario_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_blog.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_usuario', models.CharField(max_length=100)),
                ('comentario', models.TextField()),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_blog.usuario')),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_blog.post')),
            ],
        ),
    ]
